#!/usr/bin/env bash

set -euo pipefail option
cd ${0%/*}

tag=21-slim-faststart

# Run the Integration Test DB
docker run -d -p 1521:1521 -e ORACLE_PASSWORD=password -v ./src/test/resources/db/dba_users:/container-entrypoint-initdb.d gvenzl/oracle-xe:"${tag}"